name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Clone Shinonome
      run: |
        git clone -b upstream https://salsa.debian.org/fonts-team/xfonts-shinonome.git
    - name: Create FMT_FNT.ROM
      run: |
        python 16dot.py --graphics bdf/towns16g.bdf --jisx0201 ./xfonts-shinonome/bdf/shnm8x16r.bdf --jisx0208 ./xfonts-shinonome/bdf/shnmk16min.bdf --out FMT_FNT.ROM
    - name: Upload FMT_FNT.ROM
      uses: actions/upload-artifact@v2
      with:
        name: FMT_FNT.ROM
        path: FMT_FNT.ROM
    - name: Create FMT_SYS0.F12
      run: |
        python 12dot.py --graphics bdf/towns12g.bdf --jisx0201 ./xfonts-shinonome/bdf/shnm6x12r.bdf --jisx0208 ./xfonts-shinonome/bdf/shnmk12.bdf --out FMT_SYS0.F12
    - name: Upload FMT_SYS0.F12
      uses: actions/upload-artifact@v2
      with:
        name: FMT_SYS0.F12
        path: FMT_SYS0.F12
